FROM alpine:3.10

#ARG SSH_PRIVATE_KEY
#RUN apt-get update && apt-get upgrade -y && apt-get install python3 python3-pip curl build-essential -y
#RUN curl -sL https://deb.nodesource.com/setup_16.x  | bash
#RUN apt-get -yq install nodejs
ENV PYTHONUNBUFFERED=1
RUN apk update && apk upgrade
RUN apk add --no-cache python3=3.7.10-r0 py3-numpy py3-numpy-f2py libpng libjpeg-turbo libstdc++ && ln -sf python3 /usr/bin/python
RUN python3 -m ensurepip
RUN pip3 install --no-cache --upgrade pip setuptools
#RUN pip3 install tensorflow
#RUN python3 -c "import tensorflow"
RUN apk add --no-cache openssh-client git 
RUN apk add --update nodejs npm
WORKDIR /server

COPY . /server

RUN npm install -g npm
RUN npm install

ADD tfjs-pipeline-repo-key /
RUN \
  chmod 600 /tfjs-pipeline-repo-key && \  
  echo "IdentityFile /tfjs-pipeline-repo-key" >> /etc/ssh/ssh_config && \  
  echo -e "StrictHostKeyChecking no" >> /etc/ssh/ssh_config && \
  git clone git@github.com:tensorflow/models.git  